imports:
    - { resource: tables.yml }

services:
    chris1278.cookie.ext_cookie:
        class: chris1278\cookie\core\chris1278_db
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '%tables.ext_cookie%'

    chris1278.cookie.listener:
        class: chris1278\cookie\event\listener
        arguments:
            - '@chris1278.cookie.ext_cookie'
            - '@config'
            - '@template'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
